### ISSUE TITLE
import.meta SyntaxError

### ISSUE THREAD

**Issue by arthuredelstein** [arthuredelstein/hakk#16]
`import.meta` is documented here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta

Currently we see

```
if (import.meta.url === `file://${process.argv[1]}`) {                               
           ^^^^                                                                      
                                                                                     
SyntaxError: Cannot use 'import.meta' outside a module                               
    at new Script (node:vm:100:7)                                                    
    at Object.createScript (node:vm:265:10)                                          
    at defaultEval (node:repl:504:23)                                                
    at bound (node:domain:433:15)                                                    
    at runBound (node:domain:444:12)                                                 
    at REPLServer.newEval [as eval] (/home/arthuredelstein/hakk/index.js:254:7)      
    at previousFragments (/home/arthuredelstein/hakk/index.js:218:22)                
    at new Promise (<anonymous>)                                                     
    at evaluateChangedCodeFragments (/home/arthuredelstein/hakk/index.js:217:15)     
                                                                                     
```

**Comment by arthuredelstein** [comment]
Fixed in
